name: Deploy dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      docker_compose_file: docker-compose.dev.yml
      env_file: .env.development
    secrets: inherit
